project:
  type: website
  output-dir: docs
  title: "Conspect"
  render:
    - "*.qmd"
    - "!iee_typst/Edy.qmd"
lang: ru

website:
  page-navigation: true
  back-to-top-navigation: true
  reader-mode: true
  open-graph: true

  sidebar:
    style: "floating"
    background: light
    alignment: left
    collapse-level: 1
    pinned: true

    contents:
      - section: "EDX"
        contents:
          - text: "PART 1: R Basic"
            file: 1.R_basic.qmd
          - text: "PART 2: Visualization"
            file: 2.Visualization.qmd
          - text: "PART 3: Probability"
            file: 3.Probability.qmd
          - text: "PART 4: Inference"
            file: 4.Inference.qmd
          - text: "PART 5: Productivity Tools"
            file: 5. Data Science Productivity Tools.qmd
          - text: "PART 6: Wrangling"
            file: 6.Wrangling.qmd
          - text: "PART 7: Linear Regression"
            file: 7. Linear Regression.qmd
          - text: "PART 8: Machine Learning"
            file: 8. Machine Learning.qmd

      - section: "DataCamp"
        contents:
          - text: "Foundation to Probability"
            file: DataCamp_Foundation to probability.qmd

      - section: "SkillFactory"
        contents:
          - text: "SkillFactory"
            file: SkillFactory.qmd

  navbar:
    pinned: false
    search: true
    collapse-below: "sm"
    left:
      - text: "EDX"
        menu:
          - text: "PART 1: R Basic"
            file: 1.R_basic.qmd
          - text: "PART 2: Visualization"
            file: 2.Visualization.qmd
          - text: "PART 3: Probability"
            file: 3.Probability.qmd
          - text: "PART 4: Inference"
            file: 4.Inference.qmd
          - text: "PART 5: Productivity Tools"
            file: 5. Data Science Productivity Tools.qmd
          - text: "PART 6: Wrangling"
            file: 6.Wrangling.qmd
          - text: "PART 7: Linear Regression"
            file: 7. Linear Regression.qmd
          - text: "PART 8: Machine Learning"
            file: 8. Machine Learning.qmd

      - text: "DataCamp"
        file: DataCamp_Foundation to probability.qmd

      - text: "SkillFactory"
        file: SkillFactory.qmd

    tools:
      - icon: github
        menu:
          - text: Source Code
            url: https://github.com/Edy888

  page-footer:
    left: "Copyright 2024, Eduard Soldatkin"
    right:
      - icon: github
        href: https://github.com/Edy888
    border: false
    background: dark

format:
  html:
    grid:
      sidebar-width: 340px
      body-width: 940px
      margin-width: 340px
      gutter-width: 1.5rem
    theme: flatly
